"""Type stub for the compiled `pcl_rustic._core` PyO3 extension module.

This is the exact-dtype layer: unlike the `pcl_rustic` Python wrapper, every
method here demands the pinned dtype and raises rather than coercing. See
docs/plans/adr-0002 for the dimension/dtype contract and docs/plans/adr-0001
for device selection.
"""

from typing import ClassVar

import numpy as np
from numpy.typing import NDArray

class PointCloud:
    def __new__(cls) -> PointCloud: ...
    @staticmethod
    def from_xyz(
        xyz: NDArray[np.float32]
        | NDArray[np.float64]
        | NDArray[np.int32]
        | NDArray[np.int64],
    ) -> PointCloud: ...
    @staticmethod
    def read(
        path: str,
        columns: dict[str, str] | None = None,
        delimiter: str = ",",
    ) -> PointCloud: ...
    def write(
        self,
        path: str,
        columns: dict[str, str] | None = None,
        delimiter: str = ",",
    ) -> None: ...
    def get_dim(self, name: str) -> NDArray[np.generic]: ...
    def set_dim(self, name: str, values: NDArray[np.generic]) -> None: ...
    def has_dim(self, name: str) -> bool: ...
    def remove_dim(self, name: str) -> None: ...
    def dim_names(self) -> list[str]: ...
    def dim_dtypes(self) -> dict[str, str]: ...
    def add_extra_dim(self, name: str, dtype: str) -> None: ...
    def transform(self, matrix: NDArray[np.float64]) -> PointCloud: ...
    def rigid_transform(
        self,
        rotation: NDArray[np.float64],
        translation: NDArray[np.float64],
    ) -> PointCloud: ...
    def voxel_downsample(
        self,
        voxel_size: float,
        strategy: int = ...,
        seed: int | None = None,
    ) -> PointCloud: ...
    def to_device(self, device: str) -> PointCloud: ...
    @property
    def device(self) -> str: ...
    def clone(self) -> PointCloud: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class DownsampleStrategy:
    NEAREST_TO_CENTROID: ClassVar[int]
    RANDOM: ClassVar[int]

def available_devices() -> list[str]: ...
def default_device() -> str: ...
